/**
 * This code was generated by Builder.io
 */
import { FC } from "react";
import { PriceItemProps } from "./types";

export const PriceItem: FC<PriceItemProps> = ({ label, price }) => (
  <div className="flex gap-10 text-3xl">
    <div>
      <span className="text-white uppercase">{label[0]}</span>
      <span className="text-white">{label.slice(1)} </span>
    </div>
    <div className="text-white">{price}</div>
  </div>
);
